### ISSUE TITLE
python keywords (e.g. from, for) not working as names

### ISSUE THREAD

**Issue by orlof** [danthedeckie/simpleeval#49]
`simple_eval("from", names={"from": 1})`
raises SyntaxError: invalid syntax

I suppose most (if not all) keywords and names could be identified based on their position in the expression.

**Comment by danthedeckie** [comment]
Hm.  That's an interesting thought.

To me it's kind of obvious that it's not going to work - and because we're using the Python "ast" Parser which does all keywords etc. internally - it would require re-writing a custom parser which was clever enough.

One could potentially write a preprocessor of some sort that would attempt to replace keywords - but it would essentially have to parse it all first to ensure it wasn't replacing part of a string, or similar.

I'm not going to write a custom parser for the subset of python that simpleeval understands.

However - it's not obvious to end users that it's not going to work.  And it's certainly not documented nicely.
